theme: jekyll-theme-minimal
title: Learning
github.is_project_page: false
is_project_page: true
logo: https://avatars3.githubusercontent.com/u/39960794?s=460&v=4
show_downloads: true
description: This is a test text for a long description of the project. I am a Physicist of the Universidad Nacional de Colombia. Interested on Programming & Physics, This includes data analysis, machine learning algorithms, deep learning programming, but also dynamical systems analysis as theoretical as computational
